Repository Beyond-Article1/MediHub-BE, pull requests merged in 2024-12, with the labels that each got.

#7 docs: #6 Readme 초안 작성
  README.md
Labels: :memo: docs

#12 Delete .idea directory
  .idea/.gitignore
  .idea/.name
  .idea/MediHub-BE.iml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
Labels: :wastebasket: delete

#13 Feat/base time entity/#11
  .gitignore
  src/main/java/mediHub_be/common/aggregate/entity/BaseCreateDeleteEntity.java
  src/main/java/mediHub_be/common/aggregate/entity/BaseFullEntity.java
  src/main/java/mediHub_be/common/aggregate/entity/CreateTimeEntity.java
Labels: :new: feat, :wastebasket: delete

#15 fix: #14 응답객체 관련 코드 변경 및 에러코드 수정
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build.gradle
  src/main/java/mediHub_be/common/exception/ErrorCode.java
  src/main/java/mediHub_be/common/exception/ErrorResponse.java
  src/main/java/mediHub_be/common/exception/ExceptionDTO.java
  src/main/java/mediHub_be/common/exception/GlobalExceptionHandler.java
  src/main/java/mediHub_be/common/response/ApiResponse.java
  src/main/java/mediHub_be/test/controller/TestController.java
  src/main/resources/application.yml
Labels: :hammer_and_wrench: fix, :new: feat

#17 feat: #16 도커 컴포즈로 환경 세팅 및 env 파일 설정
  .gitignore
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build.gradle
  docker-compose.yml
  src/main/resources/application.yml
Labels: :new: feat

#30 [FEAT] 부서 CRUD 완성
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/mediHub_be/dept/controller/DeptController.java
  src/main/java/mediHub_be/part/controller/PartController.java
  src/main/java/mediHub_be/part/conttoller/PartController.java
  src/main/java/mediHub_be/part/dto/PartDTO.java
  src/main/java/mediHub_be/part/entity/Part.java
  src/main/java/mediHub_be/part/repository/PartRepository.java
  src/main/java/mediHub_be/part/service/PartService.java
Labels: :new: feat

#35 [REFACTOR] user 엔터티 수정
  src/main/java/mediHub_be/part/entity/Part.java
  src/main/java/mediHub_be/user/entity/User.java
Labels: :recycle: refactor

#34 [FEAT] CpVersion 요구사항 명세서 API 구현
  .gitignore
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/dto/CpDTO.java
  src/main/java/mediHub_be/cp/dto/CpVersionDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpDTO.java
  src/main/java/mediHub_be/cp/entity/Cp.java
  src/main/java/mediHub_be/cp/entity/CpOpinion.java
  src/main/java/mediHub_be/cp/entity/CpOpinionLocation.java
  src/main/java/mediHub_be/cp/entity/CpOpinionVote.java
  src/main/java/mediHub_be/cp/entity/CpSearchCategory.java
  src/main/java/mediHub_be/cp/entity/CpSearchCategoryData.java
  src/main/java/mediHub_be/cp/entity/CpSearchData.java
  src/main/java/mediHub_be/cp/entity/CpVersion.java
  src/main/java/mediHub_be/cp/repository/CpVersionRepository.java
  src/main/java/mediHub_be/cp/service/CpService.java
Labels: :new: feat

#38 Feat/sse/#22
  .gradle/8.8/checksums/checksums.lock
  .gradle/8.8/checksums/sha1-checksums.bin
  .gradle/8.8/dependencies-accessors/gc.properties
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileChanges/last-build.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
  build.gradle
  src/main/java/mediHub_be/config/BeanConfig.java
  src/main/java/mediHub_be/config/test
  src/main/java/mediHub_be/notify/controller/NotifyController.java
  src/main/java/mediHub_be/notify/dto/NotifyDTO.java
  src/main/java/mediHub_be/notify/entity/NotiReadStatus.java
  src/main/java/mediHub_be/notify/entity/NotiType.java
  src/main/java/mediHub_be/notify/entity/Notify.java
  src/main/java/mediHub_be/notify/repository/NotifyRepository.java
  src/main/java/mediHub_be/notify/repository/SseRepository.java
  src/main/java/mediHub_be/notify/repository/SseRepositoryImpl.java
  src/main/java/mediHub_be/notify/service/NotifyService.java
  src/main/java/mediHub_be/test/controller/TestController.java
  src/main/java/mediHub_be/test/controller/test
  src/main/java/mediHub_be/test/dto/test
  src/main/java/mediHub_be/test/entity/test
  src/main/java/mediHub_be/test/service/test
  src/main/resources/application.yml
  src/test/java/mediHub_be/src/test/notify/controller/NotifyControllerTest.java
Labels: :hammer_and_wrench: fix, :new: feat

#39 hotFix: JPA 오류 수정
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/repository/CpVersionRepository.java
  src/main/java/mediHub_be/cp/service/CpService.java
Labels: :hammer_and_wrench: fix

#42 [FEAT] 유저 로그인 기능
  build.gradle
  src/main/java/mediHub_be/PasswordEncryptor.java
  src/main/java/mediHub_be/config/AppConfig.java
  src/main/java/mediHub_be/config/SecurityConfig.java
  src/main/java/mediHub_be/config/SwaggerConfig.java
  src/main/java/mediHub_be/security/dto/ExceptionResponse.java
  src/main/java/mediHub_be/security/dto/LoginRequest.java
  src/main/java/mediHub_be/security/filter/CustomAuthenticationFilter.java
  src/main/java/mediHub_be/security/filter/JwtFilter.java
  src/main/java/mediHub_be/security/handler/JwtAccessDeniedHandler.java
  src/main/java/mediHub_be/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/mediHub_be/security/handler/LoginFailureHandler.java
  src/main/java/mediHub_be/security/handler/LoginSuccessHandler.java
  src/main/java/mediHub_be/security/util/JwtUtil.java
  src/main/java/mediHub_be/user/controller/UserController.java
  src/main/java/mediHub_be/user/dto/UserDTO.java
  src/main/java/mediHub_be/user/entity/User.java
  src/main/java/mediHub_be/user/repository/UserRepository.java
  src/main/java/mediHub_be/user/service/UserService.java
  src/main/resources/application.yml
Labels: :new: feat

#43 [FEAT] 케이스 공유 등록, 수정, 삭제 구현
  src/main/java/mediHub_be/board/entity/Keyword.java
  src/main/java/mediHub_be/board/repository/FlagRepository.java
  src/main/java/mediHub_be/board/service/FlagService.java
  src/main/java/mediHub_be/board/service/KeywordService.java
  src/main/java/mediHub_be/case_sharing/controller/CaseSharingController.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingCreateRequestDTO.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingDetailDTO.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingUpdateRequestDTO.java
  src/main/java/mediHub_be/case_sharing/dto/VersionDTO.java
  src/main/java/mediHub_be/case_sharing/entity/CaseSharing.java
  src/main/java/mediHub_be/case_sharing/entity/CaseSharingGroup.java
  src/main/java/mediHub_be/case_sharing/entity/Version.java
  src/main/java/mediHub_be/case_sharing/repository/CaseSharingGroupRepository.java
  src/main/java/mediHub_be/case_sharing/repository/CaseSharingRepository.java
  src/main/java/mediHub_be/case_sharing/repository/TemplateRepository.java
  src/main/java/mediHub_be/case_sharing/repository/VersionRepository.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingService.java
  src/main/java/mediHub_be/common/aggregate/entity/BaseCreateDeleteEntity.java
  src/main/java/mediHub_be/part/entity/Part.java
  src/main/java/mediHub_be/part/service/PartService.java
  src/main/resources/dml.sql
Labels: :new: feat, :recycle: refactor

#44 [FEAT] SSE로 알림 생성
  src/main/java/mediHub_be/notify/controller/NotifyController.java
  src/main/java/mediHub_be/notify/entity/Notify.java
  src/main/java/mediHub_be/notify/service/NotifyService.java
Labels: :hammer_and_wrench: fix, :new: feat

#47 [FEAT] CpVersion 요구사항 API 구현
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/entity/Cp.java
  src/main/java/mediHub_be/cp/entity/CpOpinion.java
  src/main/java/mediHub_be/cp/entity/CpSearchCategory.java
  src/main/java/mediHub_be/cp/entity/CpSearchCategoryData.java
  src/main/java/mediHub_be/cp/entity/CpVersion.java
  src/main/java/mediHub_be/cp/repository/CpVersionRepository.java
  src/test/java/mediHub_be/src/test/cp/controller/CpControllerTest.java
  src/test/java/mediHub_be/src/test/cp/service/CpServiceTest.java
Labels: :new: feat

#49 [FEAT] 시큐리티 유틸
  build.gradle
  src/main/java/mediHub_be/config/SecurityConfig.java
  src/main/java/mediHub_be/security/util/SecurityUtil.java
Labels: :new: feat

#54 [FEAT] Noti 단일, 다중 형성 및 추상화
  build.gradle
  docker-compose.yml
  src/main/java/mediHub_be/config/SecurityConfig.java
  src/main/java/mediHub_be/notify/controller/NotifyController.java
  src/main/java/mediHub_be/notify/dto/NotifyDTO.java
  src/main/java/mediHub_be/notify/entity/NotiType.java
  src/main/java/mediHub_be/notify/entity/Notify.java
  src/main/java/mediHub_be/notify/service/NotifyService.java
  src/main/java/mediHub_be/notify/service/NotifyServiceImlp.java
  src/main/java/mediHub_be/security/util/SecurityUtil.java
  src/main/resources/application.yml
Labels: :hammer_and_wrench: fix, :new: feat, :recycle: refactor

#57 [FIX] NotifyController service 의존성 변경
  src/main/java/mediHub_be/notify/controller/NotifyController.java
Labels: :hammer_and_wrench: fix

#60 [FEAT] #55 도커컴포즈, yml 레디스 설정 추가 및 주석
  build.gradle
  docker-compose.yml
  src/main/java/mediHub_be/notify/controller/NotifyController.java
  src/main/java/mediHub_be/notify/service/NotifyServiceImlp.java
  src/main/resources/application.yml
Labels: :hammer_and_wrench: fix, :new: feat

#62 [FEAT] 케이스 공유 북마크, 조회수 기능 구현
  src/main/java/mediHub_be/board/Util/ViewCountManager.java
  src/main/java/mediHub_be/board/entity/Bookmark.java
  src/main/java/mediHub_be/board/entity/Prefer.java
  src/main/java/mediHub_be/board/repository/BookmarkRepository.java
  src/main/java/mediHub_be/board/service/BookmarkService.java
  src/main/java/mediHub_be/board/service/FlagService.java
  src/main/java/mediHub_be/board/service/KeywordService.java
  src/main/java/mediHub_be/case_sharing/controller/CaseSharingController.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingCommentDTO.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingDetailDTO.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingListDTO.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingVersionListDTO.java
  src/main/java/mediHub_be/case_sharing/entity/CaseSharing.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingService.java
  src/main/resources/application.yml
  src/main/resources/dml.sql
Labels: :new: feat, :recycle: refactor

#64 [FEAT] 케이스 공유 댓글 기능 구현
  src/main/java/mediHub_be/case_sharing/controller/CaseSharingCommentController.java
  src/main/java/mediHub_be/case_sharing/controller/CaseSharingController.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingCommentDetailDTO.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingCommentListDTO.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingCommentRequestDTO.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingDetailDTO.java
  src/main/java/mediHub_be/case_sharing/entity/CaseSharingComment.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingCommentService.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingService.java
Labels: :new: feat, :recycle: refactor, :1234: chore

#65 [FEAT] CP 의견 요구사항 API 구현
  src/main/java/mediHub_be/board/service/FlagService.java
  src/main/java/mediHub_be/common/exception/ErrorCode.java
  src/main/java/mediHub_be/common/exception/GlobalExceptionHandler.java
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/dto/CpOpinionDTO.java
  src/main/java/mediHub_be/cp/dto/RequestCpOpinionDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpOpinionDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpOpinionWithKeywordListDTO.java
  src/main/java/mediHub_be/cp/entity/CpOpinion.java
  src/main/java/mediHub_be/cp/entity/CpOpinionLocation.java
  src/main/java/mediHub_be/cp/repository/CpOpinionRepository.java
  src/main/java/mediHub_be/cp/repository/CpVersionRepository.java
  src/main/java/mediHub_be/cp/service/CpOpinionService.java
  src/main/resources/application.yml
Labels: :new: feat

#69 [FEAT] DDL 생성, DML 수정
  src/main/resources/Schema.sql
  src/main/resources/data.sql
  src/main/resources/dml.sql
Labels: :new: feat, :1234: chore

#71 [FEAT] 케이스 공유 템플릿 CRUD
  src/main/java/mediHub_be/board/entity/Picture.java
  src/main/java/mediHub_be/board/repository/PictureRepository.java
  src/main/java/mediHub_be/case_sharing/controller/TemplateController.java
  src/main/java/mediHub_be/case_sharing/dto/TemplateDetailDTO.java
  src/main/java/mediHub_be/case_sharing/dto/TemplateListDTO.java
  src/main/java/mediHub_be/case_sharing/dto/TemplateRequestDTO.java
  src/main/java/mediHub_be/case_sharing/entity/Template.java
  src/main/java/mediHub_be/case_sharing/repository/CaseSharingGroupRepository.java
  src/main/java/mediHub_be/case_sharing/repository/CaseSharingRepository.java
  src/main/java/mediHub_be/case_sharing/repository/TemplateRepository.java
  src/main/java/mediHub_be/case_sharing/service/TemplateService.java
Labels: :hammer_and_wrench: fix, :new: feat

#74 [FEAT] CpOpinion 요구사항 API 개발
  src/main/java/mediHub_be/common/exception/ErrorCode.java
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/dto/CpOpinionLocationDTO.java
  src/main/java/mediHub_be/cp/dto/RequestCpOpinionLocationDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpDTO.java
  src/main/java/mediHub_be/cp/entity/CpOpinionLocation.java
  src/main/java/mediHub_be/cp/repository/CpOpinionLocationRepository.java
  src/main/java/mediHub_be/cp/repository/CpVersionRepository.java
  src/main/java/mediHub_be/cp/service/CpOpinionLocationService.java
  src/main/java/mediHub_be/cp/service/CpService.java
Labels: :m: test

#75 [Feat] Notify DTO 수정 및 CRUD 생성
  src/main/java/mediHub_be/common/exception/ErrorCode.java
  src/main/java/mediHub_be/notify/controller/NotifyController.java
  src/main/java/mediHub_be/notify/dto/NotifyDTO.java
  src/main/java/mediHub_be/notify/entity/Notify.java
  src/main/java/mediHub_be/notify/repository/NotifyRepository.java
  src/main/java/mediHub_be/notify/service/NotifyServiceImlp.java
Labels: :hammer_and_wrench: fix, :new: feat

#80 [FEAT] CP 의견 위치 생성, 수정, 삭제 API 개발
  src/main/java/mediHub_be/common/exception/ErrorCode.java
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/dto/RequestCpOpinionLocationDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpOpinionLocationDTO.java
  src/main/java/mediHub_be/cp/entity/CpOpinionLocation.java
  src/main/java/mediHub_be/cp/repository/CpOpinionLocationRepository.java
  src/main/java/mediHub_be/cp/service/CpOpinionLocationService.java
  src/main/java/mediHub_be/cp/service/CpOpinionService.java
  src/main/java/mediHub_be/cp/service/CpService.java
Labels: :new: feat

#81 [FEAT] WebSocket Stomp 연결 설정
  build.gradle
  src/main/java/mediHub_be/chat/StompHandler.java
  src/main/java/mediHub_be/config/WebSocketConfig.java
Labels: :new: feat

#86 [FEAT] 채팅방 관련 기능 구현
  src/main/java/mediHub_be/chat/controller/ChatController.java
  src/main/java/mediHub_be/chat/controller/ChatroomController.java
  src/main/java/mediHub_be/chat/dto/ChatMessageDTO.java
  src/main/java/mediHub_be/chat/dto/ChatroomDTO.java
  src/main/java/mediHub_be/chat/dto/ChatroomInfoDTO.java
  src/main/java/mediHub_be/chat/dto/UpdateChatroomDTO.java
  src/main/java/mediHub_be/chat/entity/Chat.java
  src/main/java/mediHub_be/chat/entity/ChatMessage.java
  src/main/java/mediHub_be/chat/entity/Chatroom.java
  src/main/java/mediHub_be/chat/repository/ChatMessageRepository.java
  src/main/java/mediHub_be/chat/repository/ChatRepository.java
  src/main/java/mediHub_be/chat/repository/ChatroomRepository.java
  src/main/java/mediHub_be/chat/service/ChatService.java
  src/main/java/mediHub_be/chat/service/ChatroomService.java
  src/main/java/mediHub_be/common/exception/ErrorCode.java
  src/main/java/mediHub_be/user/entity/User.java
  src/main/java/mediHub_be/user/repository/UserRepository.java
  src/main/resources/data.sql
Labels: :new: feat

#87 [CHORE] DDL, DML 수정
  src/main/resources/Schema.sql
  src/main/resources/data.sql
Labels: :1234: chore

#88 [CHORE] DDL, DML 수정
  src/main/resources/Schema.sql
  src/main/resources/data.sql
Labels: :1234: chore

#91 [FEAT] 챗봇 기능 연동
  src/main/java/mediHub_be/board/service/KeywordService.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingCommentService.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingService.java
  src/main/java/mediHub_be/chatbot/controller/ChatbotRestController.java
  src/main/java/mediHub_be/chatbot/controller/ChatbotWebSocketController.java
  src/main/java/mediHub_be/chatbot/dto/ChatbotRequestDTO.java
  src/main/java/mediHub_be/chatbot/dto/ChatbotResponseDTO.java
  src/main/java/mediHub_be/chatbot/dto/ChoiceDTO.java
  src/main/java/mediHub_be/chatbot/dto/MessageDTO.java
  src/main/java/mediHub_be/chatbot/entity/ChatbotMessage.java
  src/main/java/mediHub_be/chatbot/entity/ChatbotSession.java
  src/main/java/mediHub_be/chatbot/repository/ChatbotMessageRepository.java
  src/main/java/mediHub_be/chatbot/repository/ChatbotSessionRepository.java
  src/main/java/mediHub_be/chatbot/service/ChatbotRestService.java
  src/main/java/mediHub_be/chatbot/service/ChatbotWebSocketService.java
  src/main/java/mediHub_be/config/ChatbotConfig.java
  src/main/java/mediHub_be/config/ChatbotWebSocketConfig.java
  src/main/resources/application.yml
Labels: :hammer_and_wrench: fix, :new: feat, :recycle: refactor

#93 [FEAT] 익명 게시판 조회, 등록, 수정, 삭제 구현
  build.gradle
  src/main/java/mediHub_be/amazonS3/service/AmazonS3Service.java
  src/main/java/mediHub_be/anonymousBoard/controller/AnonymousBoardController.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardCreateRequestDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardDetailDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardKeywordDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardListDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardUpdateRequestDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/FlagDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/PictureDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/RequestPicture.java
  src/main/java/mediHub_be/anonymousBoard/entity/AnonymousBoard.java
  src/main/java/mediHub_be/anonymousBoard/repository/AnonymousBoardRepository.java
  src/main/java/mediHub_be/anonymousBoard/service/AnonymousBoardService.java
  src/main/java/mediHub_be/board/entity/Keyword.java
  src/main/java/mediHub_be/board/entity/Picture.java
  src/main/java/mediHub_be/board/repository/FlagRepository.java
  src/main/java/mediHub_be/board/repository/PictureRepository.java
  src/main/java/mediHub_be/case_sharing/service/TemplateService.java
  src/main/java/mediHub_be/config/S3Config.java
Labels: :new: feat, :1234: chore

#96 [FEAT] 익명 게시판 댓글 조회, 등록, 수정, 삭제 구현
  src/main/java/mediHub_be/anonymousBoard/controller/AnonymousBoardController.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardCommentListDTO.java
  src/main/java/mediHub_be/anonymousBoard/service/AnonymousBoardService.java
  src/main/java/mediHub_be/board/entity/Comment.java
  src/main/java/mediHub_be/board/repository/CommentRepository.java
Labels: :new: feat, :1234: chore

#100 [CHORE] Amazon S3 수정
  src/main/java/mediHub_be/amazonS3/service/AmazonS3Service.java
  src/main/java/mediHub_be/anonymousBoard/service/AnonymousBoardService.java
  src/main/java/mediHub_be/common/exception/ErrorCode.java
Labels: :1234: chore

#101 [REFACTOR] DB 테이블명, 구조 및 컬럼명 변경
  src/main/java/mediHub_be/anonymousBoard/dto/FlagDTO.java
  src/main/java/mediHub_be/anonymousBoard/service/AnonymousBoardService.java
  src/main/java/mediHub_be/board/entity/Flag.java
  src/main/java/mediHub_be/board/repository/FlagRepository.java
  src/main/java/mediHub_be/board/repository/KeywordRepository.java
  src/main/java/mediHub_be/board/service/BookmarkService.java
  src/main/java/mediHub_be/board/service/FlagService.java
  src/main/java/mediHub_be/board/service/KeywordService.java
  src/main/java/mediHub_be/board/service/PreferService.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingService.java
  src/main/java/mediHub_be/case_sharing/service/TemplateService.java
  src/main/java/mediHub_be/config/SecurityConfig.java
  src/main/java/mediHub_be/cp/service/CpOpinionService.java
  src/main/java/mediHub_be/user/entity/User.java
  src/main/resources/Schema.sql
  src/main/resources/data.sql
Labels: :hammer_and_wrench: fix, :recycle: refactor, :wastebasket: delete

#102 [FEAT] CP 검색 카테고리 요구사항 API 개발
  src/main/java/mediHub_be/common/exception/ErrorCode.java
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/dto/ResponseCpSearchCategoryDTO.java
  src/main/java/mediHub_be/cp/entity/CpSearchCategory.java
  src/main/java/mediHub_be/cp/repository/CpSearchCategoryRepository.java
  src/main/java/mediHub_be/cp/service/CpSearchCategoryService.java
Labels: :new: feat

#104 [FEAT] CP 검색 카테고리 데이터 요구사항 API 개발
  src/main/java/mediHub_be/common/exception/ErrorCode.java
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/dto/ResponseCpSearchCategoryDataDTO.java
  src/main/java/mediHub_be/cp/entity/CpSearchCategoryData.java
  src/main/java/mediHub_be/cp/repository/CpSearchCategoryDataRepository.java
  src/main/java/mediHub_be/cp/service/CpSearchCategoryService.java
Labels: :new: feat

#110 [FIX] CP 조회수 로직 변경
  http/login.http
  src/main/java/mediHub_be/common/exception/ErrorCode.java
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/dto/ResponseCpOpinionDTO.java
  src/main/java/mediHub_be/cp/entity/Cp.java
  src/main/java/mediHub_be/cp/entity/CpOpinion.java
  src/main/java/mediHub_be/cp/entity/CpVersion.java
  src/main/java/mediHub_be/cp/repository/CpOpinionRepository.java
  src/main/java/mediHub_be/cp/repository/CpRepository.java
  src/main/java/mediHub_be/cp/repository/CpVersionRepository.java
  src/main/java/mediHub_be/cp/service/CpOpinionService.java
  src/main/java/mediHub_be/cp/service/CpService.java
  src/test/java/mediHub_be/src/test/cp/controller/CpControllerTest.java
  src/test/java/mediHub_be/src/test/cp/service/CpServiceTest.java
Labels: :new: feat

#107 [FEAT] DDL, DML 수정
  src/main/resources/Schema.sql
  src/main/resources/data.sql
Labels: :new: feat, :1234: chore

#112 [FEAT] BeanConfig로 합치기, 찾는 형식 변경
  build.gradle
  src/main/java/mediHub_be/common/aggregate/entity/UpdateTimeEntity.java
  src/main/java/mediHub_be/common/exception/ErrorCode.java
  src/main/java/mediHub_be/config/AppConfig.java
  src/main/java/mediHub_be/config/BeanConfig.java
  src/main/java/mediHub_be/config/ChatbotConfig.java
  src/main/java/mediHub_be/config/OpenAiConfig.java
  src/main/java/mediHub_be/notify/controller/NotifyController.java
  src/main/java/mediHub_be/notify/entity/Notify.java
  src/main/java/mediHub_be/openai/controller/JournalController.java
  src/main/java/mediHub_be/openai/dto/ChatGPTRequest.java
  src/main/java/mediHub_be/openai/dto/ChatGPTResponse.java
  src/main/java/mediHub_be/openai/dto/Message.java
  src/main/java/mediHub_be/openai/dto/ResponseAbstractDTO.java
  src/main/java/mediHub_be/openai/dto/ResponsePubmedDTO.java
  src/main/java/mediHub_be/openai/entity/Journal.java
  src/main/java/mediHub_be/openai/entity/JournalSearch.java
  src/main/java/mediHub_be/openai/entity/StringListConverter.java
  src/main/java/mediHub_be/openai/repository/JournalRepository.java
  src/main/java/mediHub_be/openai/repository/JournalSearchRepository.java
  src/main/java/mediHub_be/openai/service/JournalService.java
  src/main/java/mediHub_be/openai/service/JournalServiceImpl.java
  src/main/resources/Schema.sql
  src/main/resources/application.yml
  src/main/resources/prompt.yml
Labels: :hammer_and_wrench: fix, :new: feat

#116 [FEAT] #114 논문 조회수순 조회 생성
  .gitignore
  src/main/java/mediHub_be/journal/controller/JournalController.java
  src/main/java/mediHub_be/journal/dto/ChatGPTRequest.java
  src/main/java/mediHub_be/journal/dto/ChatGPTResponse.java
  src/main/java/mediHub_be/journal/dto/Message.java
  src/main/java/mediHub_be/journal/dto/ResponseAbstractDTO.java
  src/main/java/mediHub_be/journal/dto/ResponseJournalSearchDTO.java
  src/main/java/mediHub_be/journal/dto/ResponsePubmedDTO.java
  src/main/java/mediHub_be/journal/entity/Journal.java
  src/main/java/mediHub_be/journal/entity/JournalSearch.java
  src/main/java/mediHub_be/journal/entity/StringListConverter.java
  src/main/java/mediHub_be/journal/repository/JournalRepository.java
  src/main/java/mediHub_be/journal/repository/JournalSearchRepository.java
  src/main/java/mediHub_be/journal/service/JournalService.java
  src/main/java/mediHub_be/journal/service/JournalServiceImpl.java
  src/main/java/mediHub_be/openai/repository/JournalSearchRepository.java
Labels: :hammer_and_wrench: fix, :new: feat

#122 [REFACTOR] 익명 게시판 리팩터링
  src/main/java/mediHub_be/anonymousBoard/controller/AnonymousBoardController.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardCommentDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardDetailDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardFlagDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardPictureDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardPictureRequestDTO.java
  src/main/java/mediHub_be/anonymousBoard/entity/AnonymousBoard.java
  src/main/java/mediHub_be/anonymousBoard/repository/AnonymousBoardRepository.java
  src/main/java/mediHub_be/anonymousBoard/service/AnonymousBoardService.java
  src/main/java/mediHub_be/board/entity/Picture.java
  src/main/java/mediHub_be/board/repository/FlagRepository.java
  src/main/java/mediHub_be/board/repository/KeywordRepository.java
  src/main/java/mediHub_be/board/repository/PictureRepository.java
  src/main/java/mediHub_be/board/service/PreferService.java
Labels: :recycle: refactor

#123 [FEAT] CP 의견 투표 API 개발
  src/main/java/mediHub_be/board/service/FlagService.java
  src/main/java/mediHub_be/common/exception/ErrorCode.java
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/dto/CpOpinionVoteDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpOpinionWithKeywordListAndCpOpinionVoteDTO.java
  src/main/java/mediHub_be/cp/entity/CpOpinionVote.java
  src/main/java/mediHub_be/cp/repository/CpOpinionVoteRepository.java
  src/main/java/mediHub_be/cp/service/CpOpinionService.java
  src/main/java/mediHub_be/cp/service/CpOpinionVoteService.java
Labels: :new: feat

#124 [REFACTOR] 익명 게시판 리팩터링
  src/main/java/mediHub_be/common/exception/ErrorCode.java
Labels: :recycle: refactor

#127 [FEAT] 논문 CRUD 및 조회들 완성
  docker-compose.yml
  src/main/java/mediHub_be/board/dto/BookmarkDTO.java
  src/main/java/mediHub_be/board/repository/BookmarkRepository.java
  src/main/java/mediHub_be/board/service/BookmarkService.java
  src/main/java/mediHub_be/board/service/FlagService.java
  src/main/java/mediHub_be/common/exception/ErrorCode.java
  src/main/java/mediHub_be/journal/controller/JournalController.java
  src/main/java/mediHub_be/journal/dto/ResponseJournalLogDTO.java
  src/main/java/mediHub_be/journal/repository/JournalSearchRepository.java
  src/main/java/mediHub_be/journal/service/JournalServiceImpl.java
Labels: :hammer_and_wrench: fix, :new: feat

#130 [FEAT] 게시글 본문 내 사진 첨부 기능 구현
  src/main/java/mediHub_be/board/repository/PictureRepository.java
  src/main/java/mediHub_be/board/service/PictureService.java
  src/main/java/mediHub_be/case_sharing/controller/CaseSharingController.java
  src/main/java/mediHub_be/case_sharing/controller/TemplateController.java
  src/main/java/mediHub_be/case_sharing/dto/TemplateListDTO.java
  src/main/java/mediHub_be/case_sharing/dto/TemplateRequestDTO.java
  src/main/java/mediHub_be/case_sharing/entity/CaseSharing.java
  src/main/java/mediHub_be/case_sharing/entity/Template.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingService.java
  src/main/java/mediHub_be/case_sharing/service/TemplateService.java
  src/main/java/mediHub_be/component/MultipartJackson2HttpMessageConverter.java
  src/main/resources/Schema.sql
  src/main/resources/application.yml
Labels: :new: feat, :recycle: refactor

#131 [REFACTOR] CP Controller 분리
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/controller/CpOpinionController.java
  src/main/java/mediHub_be/cp/controller/CpOpinionLocationController.java
  src/main/java/mediHub_be/cp/controller/CpOpinionVoteController.java
  src/main/java/mediHub_be/cp/controller/CpSearchCategoryController.java
  src/main/java/mediHub_be/cp/controller/CpSearchCategoryDataController.java
  src/main/java/mediHub_be/cp/controller/CpSearchDataController.java
  src/main/java/mediHub_be/cp/dto/CpSearchDataDTO.java
  src/main/java/mediHub_be/cp/dto/RequestCpSearchDataDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpSearchDataDTO.java
  src/main/java/mediHub_be/cp/entity/CpSearchData.java
  src/main/java/mediHub_be/cp/repository/CpOpinionLocationRepository.java
  src/main/java/mediHub_be/cp/repository/CpOpinionRepository.java
  src/main/java/mediHub_be/cp/repository/CpOpinionVoteRepository.java
  src/main/java/mediHub_be/cp/repository/CpRepository.java
  src/main/java/mediHub_be/cp/repository/CpSearchCategoryDataRepository.java
  src/main/java/mediHub_be/cp/repository/CpSearchCategoryRepository.java
  src/main/java/mediHub_be/cp/repository/CpSearchDataRepository.java
  src/main/java/mediHub_be/cp/repository/CpVersionRepository.java
  src/main/java/mediHub_be/cp/service/CpOpinionLocationService.java
  src/main/java/mediHub_be/cp/service/CpOpinionService.java
  src/main/java/mediHub_be/cp/service/CpOpinionVoteService.java
  src/main/java/mediHub_be/cp/service/CpSearchCategoryDataService.java
  src/main/java/mediHub_be/cp/service/CpSearchCategoryService.java
  src/main/java/mediHub_be/cp/service/CpSearchDataService.java
Labels: :recycle: refactor

#137 [FEAT] #136 userService에서 findUser 생성
  src/main/java/mediHub_be/user/service/UserService.java
Labels: :new: feat

#139 [FEAT] #138 userService에서 findByUserId 생성
  src/main/java/mediHub_be/user/service/UserService.java
Labels: :new: feat

#140 [REFACTOR] service 코드 리펙토링 및 북마크 삭제 로직 추가
  src/main/java/mediHub_be/board/repository/BookmarkRepository.java
  src/main/java/mediHub_be/board/service/BookmarkService.java
  src/main/java/mediHub_be/board/service/PictureService.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingCommentService.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingService.java
  src/main/java/mediHub_be/case_sharing/service/TemplateService.java
  src/main/java/mediHub_be/common/exception/ErrorCode.java
Labels: :new: feat, :recycle: refactor, :wastebasket: delete

#142 [FIX] [REFACTOR] CP 의견 코드 수정
  src/main/java/mediHub_be/board/service/BookmarkService.java
  src/main/java/mediHub_be/board/service/FlagService.java
  src/main/java/mediHub_be/board/service/KeywordService.java
  src/main/java/mediHub_be/board/service/PictureService.java
  src/main/java/mediHub_be/cp/controller/CpOpinionController.java
  src/main/java/mediHub_be/cp/entity/CpOpinion.java
  src/main/java/mediHub_be/cp/service/CpOpinionService.java
  src/main/java/mediHub_be/cp/service/CpOpinionVoteService.java
Labels: :hammer_and_wrench: fix, :recycle: refactor

#143 [FEAT] 팔로잉과 팔로우 기능 완성 및 스웨거 태그들 기입
  .gitignore
  src/main/java/mediHub_be/common/exception/ErrorCode.java
  src/main/java/mediHub_be/follow/controller/FollowController.java
  src/main/java/mediHub_be/follow/dto/ResponseFollowingsDTO.java
  src/main/java/mediHub_be/follow/entity/Follow.java
  src/main/java/mediHub_be/follow/repository/FollowRepository.java
  src/main/java/mediHub_be/follow/service/FollowService.java
  src/main/java/mediHub_be/follow/service/FollowServiceImpl.java
  src/main/java/mediHub_be/journal/controller/JournalController.java
  src/main/java/mediHub_be/notify/controller/NotifyController.java
Labels: :hammer_and_wrench: fix, :new: feat

#145 [FIX] #144 userseq들 수정
  src/main/java/mediHub_be/journal/controller/JournalController.java
  src/main/java/mediHub_be/journal/service/JournalService.java
  src/main/java/mediHub_be/journal/service/JournalServiceImpl.java
Labels: :hammer_and_wrench: fix

#146 [FIX] [REFACTOR] CP 의견 작성 코드 수정
  src/main/java/mediHub_be/board/repository/PictureRepository.java
  src/main/java/mediHub_be/board/service/PictureService.java
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/dto/ResponseCpDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpDetailDTO.java
  src/main/java/mediHub_be/cp/service/CpService.java
  src/main/java/mediHub_be/user/service/UserService.java
  src/test/java/mediHub_be/src/test/cp/controller/CpControllerTest.java
Labels: :hammer_and_wrench: fix, :recycle: refactor

#154 [FEAT] CP, CP 의견 북마크 기능 추가
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/controller/CpOpinionController.java
  src/main/java/mediHub_be/cp/dto/ResponseCpDTO.java
  src/main/java/mediHub_be/cp/service/CpOpinionService.java
  src/main/java/mediHub_be/cp/service/CpService.java
Labels: :new: feat

#157 [FIX] 유저 프로필사진 조회 Query 오류 수정
  src/main/java/mediHub_be/board/repository/PictureRepository.java
  src/main/java/mediHub_be/board/service/PictureService.java
  src/main/java/mediHub_be/cp/service/CpService.java
Labels: :hammer_and_wrench: fix

#159 [FEAT] 마이페이지 케이스 공유 생성 및 JPA 관련 오류 해결
  src/main/java/mediHub_be/board/repository/PictureRepository.java
  src/main/java/mediHub_be/board/service/PictureService.java
  src/main/java/mediHub_be/case_sharing/controller/CaseSharingController.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingCommentDetailDTO.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingDetailDTO.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingMyListDTO.java
  src/main/java/mediHub_be/case_sharing/repository/CaseSharingRepository.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingCommentService.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingService.java
  src/main/java/mediHub_be/chatbot/controller/ChatbotRestController.java
  src/main/java/mediHub_be/chatbot/controller/ChatbotWebSocketController.java
Labels: :hammer_and_wrench: fix, :new: feat, :recycle: refactor

#161 [REFACTOR] CP, CP 의견 코드 리펙토링
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/controller/CpOpinionController.java
  src/main/java/mediHub_be/cp/dto/ResponseCpOpinionDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpOpinionWithKeywordListAndCpOpinionVoteDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpOpinionWithKeywordListDTO.java
  src/main/java/mediHub_be/cp/service/CpOpinionService.java
  src/main/java/mediHub_be/cp/service/CpService.java
Labels: :recycle: refactor

#162 [FEAT] 관리자 메디컬라이프
  src/main/java/mediHub_be/admin/controller/AdminMedicalLifeController.java
  src/main/java/mediHub_be/admin/controller/AdminUserController.java
  src/main/java/mediHub_be/admin/dto/AdminMedicalLifeCommentDTO.java
  src/main/java/mediHub_be/admin/dto/AdminMedicalLifeDTO.java
  src/main/java/mediHub_be/admin/dto/AdminMedicalLifeDetailDTO.java
  src/main/java/mediHub_be/admin/dto/AdminMedicalLifePictureDTO.java
  src/main/java/mediHub_be/admin/service/AdminMedicalLifeService.java
Labels: :new: feat, :recycle: refactor

#167 [FEAT] CP 검색 카테고리와 검색 카테고리별 데이터 조회 기능 개발
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/controller/CpSearchCategoryController.java
  src/main/java/mediHub_be/cp/dto/ResponseCpSearchCategoryAndCpSearchCategoryDataDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpSearchCategoryDataDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseSimpleCpSearchCategoryDataDTO.java
  src/main/java/mediHub_be/cp/repository/CpSearchCategoryDataRepository.java
  src/main/java/mediHub_be/cp/repository/CpSearchCategoryRepository.java
  src/main/java/mediHub_be/cp/service/CpSearchCategoryDataService.java
  src/main/java/mediHub_be/cp/service/CpSearchCategoryService.java
Labels: :new: feat

#166 [REFACTOR] 채팅방, 채팅메시지 관련 기능 리펙토링
  src/main/java/mediHub_be/chat/controller/ChatController.java
  src/main/java/mediHub_be/chat/controller/ChatroomController.java
  src/main/java/mediHub_be/chat/dto/ResponseChatMessageDTO.java
  src/main/java/mediHub_be/chat/dto/ResponseChatUserDTO.java
  src/main/java/mediHub_be/chat/repository/ChatMessageRepository.java
  src/main/java/mediHub_be/chat/repository/ChatRepository.java
  src/main/java/mediHub_be/chat/service/ChatService.java
  src/main/java/mediHub_be/chat/service/ChatroomService.java
  src/main/java/mediHub_be/chat/service/KafkaConsumerService.java
  src/main/java/mediHub_be/chat/service/KafkaProducerService.java
  src/main/java/mediHub_be/common/exception/ErrorCode.java
  src/main/java/mediHub_be/config/KafkaProducerConfig.java
Labels: :recycle: refactor

#172 [FEAT] 메디컬 라이프 내가 쓴 메디컬 라이프 조회 추가
  src/main/java/mediHub_be/medical_life/controller/MedicalLifeController.java
  src/main/java/mediHub_be/medical_life/repository/MedicalLifeRepository.java
  src/main/java/mediHub_be/medical_life/service/MedicalLifeService.java
Labels: :new: feat

#173 [FIX] #170 로직 수정 및 비로그인 조회 생성
  src/main/java/mediHub_be/journal/controller/JournalController.java
  src/main/java/mediHub_be/journal/dto/ResponseJournalRankDTO.java
  src/main/java/mediHub_be/journal/entity/StringListConverter.java
  src/main/java/mediHub_be/journal/repository/JournalSearchRepository.java
  src/main/java/mediHub_be/journal/service/JournalService.java
  src/main/java/mediHub_be/journal/service/JournalServiceImpl.java
Labels: :hammer_and_wrench: fix, :new: feat

#169 [FIX] [TEST] CP 오류 수정
  http/login.http
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/dto/ResponseCpDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpSearchCategoryAndCpSearchCategoryDataDTO.java
  src/main/java/mediHub_be/cp/service/CpService.java
Labels: :hammer_and_wrench: fix

#175 [FIX]: #174 오타수정
  src/main/java/mediHub_be/journal/dto/ResponseJournalLogDTO.java
  src/main/java/mediHub_be/journal/dto/ResponseJournalRankDTO.java
  src/main/java/mediHub_be/journal/entity/Journal.java
Labels: :hammer_and_wrench: fix

#179 [FEAT] #176 timeFormatUtil 생성
  src/main/java/mediHub_be/common/utils/TimeFormatUtil.java
  src/test/java/mediHub_be/common/utils/TimeFormatUtilTest.java
  src/test/java/mediHub_be/src/test/cp/controller/CpControllerTest.java
Labels: :m: test, :new: feat

#180 [FIX] Test이름 명시
  src/test/java/mediHub_be/common/utils/TimeFormatUtilTest.java
Labels: :hammer_and_wrench: fix

#181 [FEAT] 회원 Redis 적용
  build.gradle
  src/main/java/mediHub_be/config/RedisConfig.java
  src/main/java/mediHub_be/config/SecurityConfig.java
  src/main/java/mediHub_be/security/controller/TokenController.java
  src/main/java/mediHub_be/security/filter/JwtFilter.java
  src/main/java/mediHub_be/security/handler/JwtAccessDeniedHandler.java
  src/main/java/mediHub_be/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/mediHub_be/security/handler/LoginFailureHandler.java
  src/main/java/mediHub_be/security/handler/LoginSuccessHandler.java
  src/main/java/mediHub_be/security/securitycustom/CustomUserDetails.java
  src/main/java/mediHub_be/security/securitycustom/CustomUserDetailsService.java
  src/main/java/mediHub_be/security/service/TokenService.java
  src/main/java/mediHub_be/security/util/JwtUtil.java
  src/main/resources/application.yml
Labels: :new: feat

#184 [FIX] Success handler 수정
  src/main/java/mediHub_be/security/handler/LoginSuccessHandler.java
Labels: :hammer_and_wrench: fix, :recycle: refactor

#186 [FEAT] 사진 저장 방식 수정 및 자잘한 오류 수정
  src/main/java/mediHub_be/amazonS3/service/AmazonS3Service.java
  src/main/java/mediHub_be/board/service/PictureService.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingService.java
  src/main/java/mediHub_be/config/SecurityConfig.java
  src/main/java/mediHub_be/dept/entity/Dept.java
  src/main/java/mediHub_be/part/controller/PartController.java
  src/main/java/mediHub_be/part/dto/PartRequestDTO.java
  src/main/java/mediHub_be/part/entity/Part.java
  src/main/java/mediHub_be/part/repository/PartRepository.java
  src/main/java/mediHub_be/part/service/PartService.java
  src/main/java/mediHub_be/ranking/entity/Ranking.java
  src/main/java/mediHub_be/user/entity/User.java
Labels: :recycle: refactor

#187 [REFACTOR] 시큐리티 코드 수정
  src/main/java/mediHub_be/config/SecurityConfig.java
  src/main/java/mediHub_be/security/controller/TokenController.java
  src/main/java/mediHub_be/security/handler/LoginSuccessHandler.java
Labels: :recycle: refactor

#189 [FEAT] [FIX] CP 백엔드 코드 개발 및 수정
  src/main/java/mediHub_be/config/SecurityConfig.java
  src/main/java/mediHub_be/cp/dto/CpOpinionLocationDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpOpinionLocationDTO.java
  src/main/java/mediHub_be/cp/entity/Cp.java
  src/main/java/mediHub_be/cp/entity/CpOpinionLocation.java
  src/main/java/mediHub_be/cp/repository/CpOpinionLocationRepository.java
  src/main/java/mediHub_be/cp/repository/CpRepository.java
  src/main/java/mediHub_be/cp/repository/CpVersionRepository.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: :hammer_and_wrench: fix, :new: feat

#190 [FIX] #182 journal return
  docker-compose.yml
  src/main/java/mediHub_be/common/exception/ErrorCode.java
  src/main/java/mediHub_be/common/response/JournalResponse.java
  src/main/java/mediHub_be/config/OpenAiConfig.java
  src/main/java/mediHub_be/config/RedisConfig.java
  src/main/java/mediHub_be/journal/controller/JournalController.java
  src/main/java/mediHub_be/journal/dto/ResponseJournalRankDTO.java
  src/main/java/mediHub_be/journal/repository/JournalSearchRepository.java
  src/main/java/mediHub_be/journal/service/JournalService.java
  src/main/java/mediHub_be/journal/service/JournalServiceImpl.java
  src/main/resources/application.yml
Labels: :hammer_and_wrench: fix

#191 [REFACTOR] 케이스 공유 등록 수정
  src/main/java/mediHub_be/board/service/PictureService.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingDetailDTO.java
  src/main/java/mediHub_be/case_sharing/dto/TemplateListDTO.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingService.java
  src/main/java/mediHub_be/case_sharing/service/TemplateService.java
Labels: :new: feat

#194 [FEAT] #193 SSE 알림 테스트 컨트롤러 추가 및 알림 확인 생성
  src/main/java/mediHub_be/notify/controller/NotifyController.java
  src/main/java/mediHub_be/notify/dto/NotifyDTO.java
  src/main/java/mediHub_be/notify/entity/Notify.java
  src/main/java/mediHub_be/notify/service/NotifyServiceImlp.java
Labels: :hammer_and_wrench: fix, :new: feat

#195 [FEAT] 웹소켓 관련 토큰 인증 기능
  docker-compose.yml
  src/main/java/mediHub_be/chat/KafkaConstants.java
  src/main/java/mediHub_be/chat/StompHandler.java
  src/main/java/mediHub_be/chat/controller/ChatController.java
  src/main/java/mediHub_be/chat/controller/ChatroomController.java
Labels: :new: feat, :1234: chore

#196 [FEAT] #193 noti 관련 DTO Entity 수정
  src/main/java/mediHub_be/notify/dto/NotifyDTO.java
  src/main/java/mediHub_be/notify/entity/Notify.java
Labels: :hammer_and_wrench: fix, :new: feat

#199 [STYLE] Amazon S3 관련 클래스 경로 수정
  src/main/java/mediHub_be/admin/service/AdminUserService.java
  src/main/java/mediHub_be/board/dto/BookmarkDTO.java
  src/main/java/mediHub_be/board/entity/Picture.java
  src/main/java/mediHub_be/board/repository/BookmarkRepository.java
  src/main/java/mediHub_be/board/service/BookmarkService.java
  src/main/java/mediHub_be/board/service/KeywordService.java
  src/main/java/mediHub_be/board/service/PictureService.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingService.java
  src/main/java/mediHub_be/config/amazonS3/AmazonS3Service.java
  src/main/java/mediHub_be/config/amazonS3/S3Config.java
  src/main/java/mediHub_be/medical_life/entity/MedicalLife.java
  src/main/java/mediHub_be/medical_life/service/MedicalLifeService.java
  src/main/java/mediHub_be/user/service/UserService.java
Labels: :rainbow: style, :1234: chore

#202 [FIX] CP 오류 수정
  src/main/java/mediHub_be/board/service/KeywordService.java
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/controller/CpOpinionController.java
  src/main/java/mediHub_be/cp/controller/CpOpinionVoteController.java
  src/main/java/mediHub_be/cp/dto/CpOpinionDTO.java
  src/main/java/mediHub_be/cp/dto/RequestCpOpinionLocationDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpOpinionDTO.java
  src/main/java/mediHub_be/cp/dto/ResponseCpVersionDTO.java
  src/main/java/mediHub_be/cp/entity/CpOpinion.java
  src/main/java/mediHub_be/cp/entity/CpOpinionLocation.java
  src/main/java/mediHub_be/cp/entity/CpOpinionVote.java
  src/main/java/mediHub_be/cp/repository/CpOpinionRepository.java
  src/main/java/mediHub_be/cp/repository/CpRepository.java
  src/main/java/mediHub_be/cp/service/CpOpinionLocationService.java
  src/main/java/mediHub_be/cp/service/CpOpinionService.java
  src/main/java/mediHub_be/cp/service/CpOpinionVoteService.java
  src/main/java/mediHub_be/cp/service/CpService.java
  src/main/resources/schema.sql
Labels: :hammer_and_wrench: fix

#204 [FEAT] ELK (Elasticsearch, Logstash, Kibana)구현
  Dockerfile
  build.gradle
  docker-compose.yml
  logstash/pipeline/logstash.conf
  src/main/java/mediHub_be/config/elasticsearch/BaseSearchDocument.java
  src/main/java/mediHub_be/config/elasticsearch/ElasticsearchConfig.java
  src/main/java/mediHub_be/config/elasticsearch/ElasticsearchIndexInitializer.java
  src/main/java/mediHub_be/elasticsearch/controller/ElasticsearchController.java
  src/main/java/mediHub_be/elasticsearch/document/AnonymousBoardDocument.java
  src/main/java/mediHub_be/elasticsearch/document/CaseSharingDocument.java
  src/main/java/mediHub_be/elasticsearch/document/CpDocument.java
  src/main/java/mediHub_be/elasticsearch/document/JournalDocument.java
  src/main/java/mediHub_be/elasticsearch/document/MedicalLifeDocument.java
  src/main/java/mediHub_be/elasticsearch/document/UserDocument.java
  src/main/java/mediHub_be/elasticsearch/repository/AnonymousBoardCustomElasticRepository.java
  src/main/java/mediHub_be/elasticsearch/repository/AnonymousBoardCustomElasticRepositoryImpl.java
  src/main/java/mediHub_be/elasticsearch/repository/AnonymousBoardElasticRepository.java
  src/main/java/mediHub_be/elasticsearch/repository/CaseSharingFindRepository.java
  src/main/java/mediHub_be/elasticsearch/repository/CpFindRepository.java
  src/main/java/mediHub_be/elasticsearch/repository/JournalFindRepository.java
  src/main/java/mediHub_be/elasticsearch/repository/MedicalLifeFindRepository.java
  src/main/java/mediHub_be/elasticsearch/repository/UserFindRepository.java
  src/main/java/mediHub_be/elasticsearch/service/ElasticsearchService.java
  src/main/resources/application.yml
  src/main/resources/elasticsearch/mappings/mappings.json
  src/main/resources/elasticsearch/settings/settings.json
  src/main/resources/logback.xml
Labels: :new: feat

#206 [FIX] 1:1 채팅방 중복 생성 방지
  src/main/java/mediHub_be/chat/controller/ChatroomController.java
  src/main/java/mediHub_be/chat/repository/ChatRepository.java
  src/main/java/mediHub_be/chat/service/ChatService.java
  src/main/java/mediHub_be/chat/service/ChatroomService.java
  src/main/java/mediHub_be/user/dto/UserSearchDTO.java
  src/main/java/mediHub_be/user/service/UserService.java
Labels: :hammer_and_wrench: fix

#209 [REFACTOR] 시큐리티 및 여러 코드 수정
  src/main/java/mediHub_be/admin/dto/AdminResponseDTO.java
  src/main/java/mediHub_be/admin/dto/AdminUpdateDTO.java
  src/main/java/mediHub_be/admin/dto/AdminUserDetailResponseDTO.java
  src/main/java/mediHub_be/admin/service/AdminUserService.java
  src/main/java/mediHub_be/board/repository/KeywordRepository.java
  src/main/java/mediHub_be/config/SecurityConfig.java
  src/main/java/mediHub_be/part/controller/PartController.java
  src/main/java/mediHub_be/part/repository/PartRepository.java
  src/main/java/mediHub_be/part/service/PartService.java
  src/main/java/mediHub_be/security/controller/TokenController.java
  src/main/java/mediHub_be/security/handler/LoginSuccessHandler.java
  src/main/java/mediHub_be/security/util/JwtUtil.java
  src/main/java/mediHub_be/user/dto/UserResponseDTO.java
  src/main/java/mediHub_be/user/entity/User.java
  src/main/java/mediHub_be/user/service/UserService.java
Labels: :hammer_and_wrench: fix, :recycle: refactor

#210 [FEAT] #193 sse
  src/main/java/mediHub_be/common/aggregate/entity/UpdateTimeEntity.java
  src/main/java/mediHub_be/journal/dto/ResponseAbstractDTO.java
  src/main/java/mediHub_be/journal/dto/ResponseJournalRankDTO.java
  src/main/java/mediHub_be/journal/dto/ResponsePubmedDTO.java
  src/main/java/mediHub_be/journal/service/JournalServiceImpl.java
Labels: :hammer_and_wrench: fix, :new: feat

#208 [FIX] CP 명 검색 쿼리 수정
  src/main/java/mediHub_be/cp/repository/CpRepository.java
  src/main/java/mediHub_be/cp/repository/CpVersionRepository.java
  src/main/java/mediHub_be/cp/service/CpOpinionService.java
  src/main/java/mediHub_be/cp/service/CpService.java
Labels: :hammer_and_wrench: fix

#212 [REFACTOR] 익명 게시판 코드 수정
  src/main/java/mediHub_be/anonymousBoard/controller/AnonymousBoardController.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardCommentDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardCommentListDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardDetailDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardFlagDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardMyPageDTO.java
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardTop3DTO.java
  src/main/java/mediHub_be/anonymousBoard/repository/AnonymousBoardRepository.java
  src/main/java/mediHub_be/anonymousBoard/service/AnonymousBoardService.java
  src/main/java/mediHub_be/board/service/FlagService.java
  src/main/java/mediHub_be/board/service/KeywordService.java
Labels: :new: feat, :recycle: refactor, :wastebasket: delete

#216 [FEAT] #215 sse 새로운 채팅방 생성시 알림 설정
  src/main/java/mediHub_be/elasticsearch/document/MedicalLifeDocument.java
  src/main/java/mediHub_be/elasticsearch/service/ElasticsearchService.java
  src/main/java/mediHub_be/notify/controller/NotifyController.java
  src/main/java/mediHub_be/notify/service/NotifyService.java
  src/main/java/mediHub_be/notify/service/NotifyServiceImlp.java
Labels: :new: feat

#218 [FEAT] 채팅 첨부파일 전송 기능
  src/main/java/mediHub_be/chat/controller/ChatController.java
  src/main/java/mediHub_be/chat/dto/ChatMessageDTO.java
  src/main/java/mediHub_be/chat/dto/ResponseChatMessageDTO.java
  src/main/java/mediHub_be/chat/entity/ChatMessage.java
  src/main/java/mediHub_be/chat/service/ChatService.java
Labels: :new: feat

#219 [FIX] CP 오류 수정
  src/main/java/mediHub_be/cp/controller/CpSearchCategoryController.java
  src/main/java/mediHub_be/cp/controller/CpSearchCategoryDataController.java
  src/main/java/mediHub_be/cp/entity/CpSearchCategory.java
  src/main/java/mediHub_be/cp/entity/CpSearchCategoryData.java
  src/main/java/mediHub_be/cp/repository/CpSearchCategoryDataRepository.java
  src/main/java/mediHub_be/cp/repository/CpSearchCategoryRepository.java
  src/main/java/mediHub_be/cp/service/CpSearchCategoryDataService.java
  src/main/java/mediHub_be/cp/service/CpSearchCategoryService.java
Labels: :hammer_and_wrench: fix

#220 [FEAT] #215 sse chat
  docker-compose.yml
  src/main/java/mediHub_be/notify/controller/NotifyController.java
  src/main/java/mediHub_be/notify/dto/NotifyDTO.java
  src/main/java/mediHub_be/notify/service/NotifyServiceImlp.java
Labels: :hammer_and_wrench: fix, :new: feat

#221 [REFACTOR] 메디컬라이프 코드 수정
  src/main/java/mediHub_be/config/SecurityConfig.java
  src/main/java/mediHub_be/medicalLife/controller/MedicalLifeController.java
  src/main/java/mediHub_be/medicalLife/dto/MedicalLifeCommentListDTO.java
  src/main/java/mediHub_be/medicalLife/dto/MedicalLifeDetailDTO.java
  src/main/java/mediHub_be/medicalLife/dto/MedicalLifeMyListDTO.java
  src/main/java/mediHub_be/medicalLife/service/MedicalLifeService.java
Labels: :recycle: refactor

#228 [FEAT] test pipeline/#223
  .github/workflows/ci.yml
  .github/workflows/main.yml
  .github/workflows/slack-notification.yml
  build.gradle
  src/test/java/mediHub_be/src/test/cp/service/CpServiceTest.java
  src/test/java/mediHub_be/src/test/notify/controller/NotifyControllerTest.java
Labels: :hammer_and_wrench: fix, :new: feat

#232 [FIX] ci properties/#231
  .github/workflows/ci.yml
Labels: :hammer_and_wrench: fix

#235 [FEAT] 케이스 공유 관련 추가 구현 및 리펙토링
  build.gradle
  src/main/java/mediHub_be/board/repository/BookmarkRepository.java
  src/main/java/mediHub_be/board/service/BookmarkService.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingCommentDetailDTO.java
  src/main/java/mediHub_be/case_sharing/entity/CaseSharingComment.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingCommentService.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingService.java
  src/main/java/mediHub_be/case_sharing/service/TemplateService.java
  src/main/java/mediHub_be/chatbot/controller/ChatbotRestController.java
  src/main/java/mediHub_be/chatbot/controller/ChatbotWebSocketController.java
  src/main/java/mediHub_be/chatbot/controller/VectorizationController.java
  src/main/java/mediHub_be/chatbot/service/ChatbotRestService.java
  src/main/java/mediHub_be/chatbot/service/ChatbotWebSocketService.java
  src/main/java/mediHub_be/chatbot/service/EmbeddingService.java
  src/main/java/mediHub_be/chatbot/service/OpenAIService.java
  src/main/java/mediHub_be/chatbot/service/TableDataService.java
  src/main/java/mediHub_be/chatbot/service/VectorDatabase.java
  src/main/java/mediHub_be/chatbot/service/VectorizationService.java
  src/main/java/mediHub_be/common/exception/ErrorCode.java
  src/main/java/mediHub_be/config/ChatbotWebSocketConfig.java
  src/main/java/mediHub_be/notify/entity/NotiType.java
  src/main/java/mediHub_be/part/repository/PartRepository.java
  src/main/java/mediHub_be/part/service/PartService.java
  src/main/java/mediHub_be/user/controller/UserController.java
  src/main/java/mediHub_be/user/service/UserService.java
Labels: :new: feat, :recycle: refactor, :1234: chore

#237 [FIX] redis관련 변경
  build.gradle
  src/main/java/mediHub_be/config/RedisConfig.java
  src/main/resources/application.yml
Labels: :hammer_and_wrench: fix

#239 [FEAT] 입장/퇴장 시 안내 메시지 전송, 채팅방별 안 읽은 메시지 개수 반환
  src/main/java/mediHub_be/chat/controller/ChatroomController.java
  src/main/java/mediHub_be/chat/dto/ResponseChatroomDTO.java
  src/main/java/mediHub_be/chat/entity/Chat.java
  src/main/java/mediHub_be/chat/entity/ChatMessage.java
  src/main/java/mediHub_be/chat/repository/ChatMessageRepository.java
  src/main/java/mediHub_be/chat/service/ChatService.java
  src/main/java/mediHub_be/chat/service/ChatroomService.java
  src/main/java/mediHub_be/user/service/UserService.java
Labels: :new: feat

#241 [FEAT] 첨부파일 목록 조회 기능
  src/main/java/mediHub_be/chat/controller/ChatController.java
  src/main/java/mediHub_be/chat/dto/ResponseAttachFileDTO.java
  src/main/java/mediHub_be/chat/repository/ChatMessageRepository.java
  src/main/java/mediHub_be/chat/repository/ChatRepository.java
  src/main/java/mediHub_be/chat/service/ChatService.java
Labels: :new: feat

#243 [FEAT] 의료 뉴스 조회 기능
  src/main/java/mediHub_be/config/NewsApiConfig.java
  src/main/java/mediHub_be/news/controller/NewsController.java
  src/main/java/mediHub_be/news/dto/NewsApiResponse.java
  src/main/java/mediHub_be/news/service/NewsService.java
Labels: :new: feat

#246 [REFACTOR] 채팅 메시지 삭제 기능 리펙토링
  src/main/java/mediHub_be/chat/service/ChatService.java
  src/main/java/mediHub_be/chat/service/KafkaProducerService.java
Labels: :recycle: refactor

#254 [FIX] SSE 연결 시간 설정
  src/main/java/mediHub_be/notify/service/NotifyServiceImlp.java
Labels: :hammer_and_wrench: fix
