Repository Beyond-Article1/MediHub-BE, pull requests merged in 2025-01, with the labels that each got.

#262 [FIX] CP 관련 클래스의 단위 테스트 불통과 오류 수정
  src/main/java/mediHub_be/board/service/PictureService.java
  src/main/java/mediHub_be/cp/controller/CpOpinionController.java
  src/main/java/mediHub_be/cp/entity/CpOpinion.java
  src/main/java/mediHub_be/cp/repository/CpVersionRepository.java
  src/main/java/mediHub_be/cp/service/CpOpinionService.java
  src/main/java/mediHub_be/cp/service/CpSearchDataService.java
  src/main/java/mediHub_be/cp/service/CpService.java
  src/test/java/mediHub_be/src/test/cp/service/CpOpinionLocationServiceTest.java
  src/test/java/mediHub_be/src/test/cp/service/CpOpinionServiceTest.java
  src/test/java/mediHub_be/src/test/cp/service/CpOpinionVoteServiceTest.java
  src/test/java/mediHub_be/src/test/cp/service/CpSearchCategoryDataServiceTest.java
  src/test/java/mediHub_be/src/test/cp/service/CpSearchCategoryServiceTest.java
  src/test/java/mediHub_be/src/test/cp/service/CpSearchDataServiceTest.java
  src/test/java/mediHub_be/src/test/cp/service/CpServiceTest.java
Labels: :hammer_and_wrench: fix

#261 [TEST] 채팅방 테스트 코드 작성
  src/test/java/mediHub_be/chat/service/ChatroomServiceTest.java
Labels: :m: test

#264 [FIX] CP 북마크 조회 시, 404 에러 발생 해결
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/entity/Cp.java
  src/main/java/mediHub_be/cp/service/CpService.java
Labels: :hammer_and_wrench: fix

#265 [REFACTOR] 시큐리티 및 메디컬 라이프
  src/main/java/mediHub_be/medicalLife/service/MedicalLifeService.java
  src/main/java/mediHub_be/security/controller/TokenController.java
  src/test/java/mediHub_be/dept/service/DeptServiceTest.java
  src/test/java/mediHub_be/part/service/PartServiceTest.java
  src/test/java/mediHub_be/ranking/service/RankingServiceTest.java
Labels: :recycle: refactor

#273 [FEAT] 채팅방 생성 SSE 이벤트 코드 순서 변경
  src/main/java/mediHub_be/chat/service/ChatroomService.java
Labels: :hammer_and_wrench: fix

#271 [FIX] CP 카테고리를 사용하여 조회 시, 중복 조회 되는 오류 수정
  src/main/java/mediHub_be/cp/repository/CpVersionRepository.java
  src/main/java/mediHub_be/cp/repository/JooqCpVersionRepository.java
Labels: :new: feat

#274 [FEAT] 익명 게시판 코드 수정
  src/main/java/mediHub_be/anonymousBoard/repository/AnonymousBoardRepository.java
  src/main/java/mediHub_be/anonymousBoard/service/AnonymousBoardService.java
Labels: :new: feat, :1234: chore

#275 [FIX] 랭킹 순위 및 유저 서비스 수정
  src/main/java/mediHub_be/admin/dto/AdminResponseDTO.java
  src/main/java/mediHub_be/admin/service/AdminUserService.java
  src/main/java/mediHub_be/user/service/UserService.java
Labels: :hammer_and_wrench: fix

#249 [REFACTOR] 챗봇 기능 리펙토링
  build.gradle
  src/main/java/mediHub_be/MediHubBeApplication.java
  src/main/java/mediHub_be/board/repository/BookmarkRepository.java
  src/main/java/mediHub_be/board/repository/PreferRepository.java
  src/main/java/mediHub_be/board/service/PictureService.java
  src/main/java/mediHub_be/case_sharing/dto/CaseSharingDetailDTO.java
  src/main/java/mediHub_be/case_sharing/dto/TemplateListDTO.java
  src/main/java/mediHub_be/case_sharing/service/CaseSharingService.java
  src/main/java/mediHub_be/case_sharing/service/TemplateService.java
  src/main/java/mediHub_be/chatbot/controller/VectorizationController.java
  src/main/java/mediHub_be/chatbot/entity/ChatbotSession.java
  src/main/java/mediHub_be/chatbot/scheduler/VectorizationScheduler.java
  src/main/java/mediHub_be/chatbot/service/ChatbotPromptLoader.java
  src/main/java/mediHub_be/chatbot/service/ChatbotRestService.java
  src/main/java/mediHub_be/chatbot/service/OpenAIService.java
  src/main/java/mediHub_be/chatbot/service/TableDataService.java
  src/main/java/mediHub_be/chatbot/service/VectorDatabase.java
  src/main/java/mediHub_be/chatbot/service/VectorizationService.java
  src/main/java/mediHub_be/config/ChatbotPromptConfig.java
  src/main/java/mediHub_be/user/controller/UserController.java
  src/main/java/mediHub_be/user/dto/UserTop3DTO.java
  src/main/java/mediHub_be/user/repository/UserRepository.java
  src/main/java/mediHub_be/user/service/UserService.java
  src/main/resources/chatbot-prompts.json
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/test/java/mediHub_be/src/test/case_sharing/service/CaseSharingCommentServiceTest.java
  src/test/java/mediHub_be/src/test/case_sharing/service/CaseSharingServiceTest.java
  src/test/java/mediHub_be/src/test/case_sharing/service/TemplateServiceTest.java
Labels: :new: feat, :recycle: refactor

#277 [REFACTOR] 시큐리티 수정
  src/main/java/mediHub_be/config/SecurityConfig.java
Labels: :recycle: refactor, :wastebasket: delete

#279 [REFACTOR] 첨부파일 제한 용량 수정, SecurityConfig 수정
  images/Admin/example.png
  images/CP/example.png
  images/CaseSharing/example.png
  images/Chat/example.png
  images/Elasticsearch/example.png
  images/Journal/example.png
  images/User/example.png
  src/main/java/mediHub_be/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: :memo: docs, :recycle: refactor

#281 [DOCS] CP 관련 gif 영상 개발
  images/CP/CP 검색 카테고리/[CP_검색_카테고리]삭제.gif
  images/CP/CP 검색 카테고리/[CP_검색_카테고리]생성.gif
  images/CP/CP 검색 카테고리/[CP_검색_카테고리]수정.gif
  images/CP/CP 검색 카테고리/[CP_검색_카테고리_데이터]삭제.gif
  images/CP/CP 검색 카테고리/[CP_검색_카테고리_데이터]생성.gif
  images/CP/CP 검색 카테고리/[CP_검색_카테고리_데이터]수정.gif
  images/CP/CP 의견/[CP]다운로드.gif
  images/CP/CP 의견/[CP]북마크(CP상세보기).gif
  images/CP/CP 의견/[CP]의견_마커_표시.gif
  images/CP/CP 의견/[CP]의견_목록_조회.gif
  images/CP/CP 의견/[CP]의견_삭제.gif
  images/CP/CP 의견/[CP]의견_상세_조회.gif
  images/CP/CP 의견/[CP]의견_생성.gif
  images/CP/CP 의견/[CP]의견_수정.gif
  images/CP/CP 의견/[CP]의견_투표_및_결과_확인.gif
  images/CP/CP/[CP]목록_조회.gif
  images/CP/CP/[CP]북마크(목록).gif
  images/CP/CP/[CP]상세_조회.gif
  images/CP/CP/[CP]조회(검색_카테고리_사용).gif
  images/CP/example.png
Labels: :memo: docs

#285 [CHORE] Elasticsearch 코드 수정
  src/main/java/mediHub_be/elasticsearch/document/CaseSharingDocument.java
Labels: :1234: chore

#287 [STYLE] 누락된 API 설명 추가
  src/main/java/mediHub_be/cp/controller/CpSearchCategoryController.java
Labels: :rainbow: style

#289 [FEAT] 검색 로직 수정
  src/main/java/mediHub_be/cp/repository/JooqCpVersionRepository.java
Labels: :new: feat

#291 [CHORE] 익명 게시판 코드 수정
  src/main/java/mediHub_be/anonymousBoard/dto/AnonymousBoardDetailDTO.java
  src/main/java/mediHub_be/anonymousBoard/service/AnonymousBoardService.java
Labels: :1234: chore

#293 [FIX] ci properties/#231
  .github/workflows/cd-v2.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/slack-notification.yml
  build.gradle
  src/main/java/mediHub_be/PasswordEncryptor.java
  src/main/java/mediHub_be/anonymousBoard/controller/AnonymousBoardController.java
  src/main/java/mediHub_be/board/controller/KeywordController.java
  src/main/java/mediHub_be/case_sharing/controller/CaseSharingCommentController.java
  src/main/java/mediHub_be/case_sharing/controller/CaseSharingController.java
  src/main/java/mediHub_be/case_sharing/controller/TemplateController.java
  src/main/java/mediHub_be/chat/KafkaConstants.java
  src/main/java/mediHub_be/chat/controller/ChatController.java
  src/main/java/mediHub_be/chat/controller/ChatroomController.java
  src/main/java/mediHub_be/chat/service/ChatService.java
  src/main/java/mediHub_be/chat/service/ChatroomService.java
  src/main/java/mediHub_be/chatbot/controller/ChatbotRestController.java
  src/main/java/mediHub_be/chatbot/controller/VectorizationController.java
  src/main/java/mediHub_be/chatbot/service/ChatbotPromptLoader.java
  src/main/java/mediHub_be/config/SecurityConfig.java
  src/main/java/mediHub_be/config/WebSocketConfig.java
  src/main/java/mediHub_be/cp/controller/CpController.java
  src/main/java/mediHub_be/cp/controller/CpOpinionController.java
  src/main/java/mediHub_be/cp/controller/CpOpinionLocationController.java
  src/main/java/mediHub_be/cp/controller/CpOpinionVoteController.java
  src/main/java/mediHub_be/cp/controller/CpSearchCategoryController.java
  src/main/java/mediHub_be/cp/controller/CpSearchCategoryDataController.java
  src/main/java/mediHub_be/cp/controller/CpSearchDataController.java
  src/main/java/mediHub_be/elasticsearch/controller/ElasticsearchController.java
  src/main/java/mediHub_be/follow/controller/FollowController.java
  src/main/java/mediHub_be/journal/controller/JournalController.java
  src/main/java/mediHub_be/journal/service/JournalServiceImpl.java
  src/main/java/mediHub_be/medicalLife/controller/MedicalLifeController.java
  src/main/java/mediHub_be/news/controller/NewsController.java
  src/main/java/mediHub_be/notify/controller/NotifyController.java
  src/main/java/mediHub_be/notify/service/NotifyServiceImlp.java
  src/main/java/mediHub_be/security/filter/CustomAuthenticationFilter.java
  src/main/java/mediHub_be/user/entity/User.java
  src/main/resources/application.yml
  src/test/java/mediHub_be/notify/service/NotifyServiceImlpTest.java
Labels: :hammer_and_wrench: fix

#296 [FIX] ci properties/#231
  .github/workflows/cd-v2.yml
  build.gradle
Labels: :hammer_and_wrench: fix

#302 [FIX] ErrorCode 번호 수정
  src/main/java/mediHub_be/common/exception/ErrorCode.java
Labels: :hammer_and_wrench: fix

#310 [FIX] CP 검색 카테고리로 검색 시 오류 해결
  src/main/java/mediHub_be/cp/repository/JooqCpVersionRepository.java
Labels: :hammer_and_wrench: fix

#313 [FIX] #312 delete workflow
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: :hammer_and_wrench: fix

#314 chore: 컬럼 정의
  src/main/java/mediHub_be/cp/entity/CpVersion.java
Labels: :rainbow: style

#316 [FIX] mongodb 시간 수정
  src/main/java/mediHub_be/chat/entity/ChatMessage.java
Labels: :hammer_and_wrench: fix

#320 [FIX] mongodb 시간 2차 수정
  src/main/java/mediHub_be/chat/service/ChatService.java
  src/main/java/mediHub_be/chat/service/ChatroomService.java
Labels: :hammer_and_wrench: fix

#323 [FIX] mongodb 시간 3차 수정
  build.gradle
  src/main/java/mediHub_be/chat/entity/ChatMessage.java
Labels: :hammer_and_wrench: fix
